name: LCBenchConstantCost
program: scripts/constant_cost.py
method: grid
parameters:
  dataset_name:
    values: ['Fashion-MNIST', 'adult', 'higgs', 'jasmine', 'vehicle', 'volkert']
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  output_standardize:
    value: True
  maximize:
    value: False
  dim:
    value: 7
  num_iteration:
    value: 400
  acquisition_function:
    values:
      - 'PBGI-D'
      - 'PBGI(5e-3)'
      - 'PBGI(1e-3)'
      - 'PBGI(5e-4)'
      - 'LogEI'
      - 'LCB'